// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrialBookingApp.Web.DataAccess;

#nullable disable

namespace TrialBookingApp.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrialBookingApp.Web.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ConfirmationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrialClassId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BookingId");

                    b.HasIndex("StudentId", "TrialClassId")
                        .IsUnique();

                    b.HasIndex("TrialClassId", "Status");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("TrialBookingApp.Web.Domain.Entities.Parent", b =>
                {
                    b.Property<Guid>("ParentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParentEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ParentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ParentId");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("TrialBookingApp.Web.Domain.Entities.PaymentAttempt", b =>
                {
                    b.Property<Guid>("PaymentAttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("AttemptDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TransactionRef")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaymentAttemptId");

                    b.HasIndex("BookingId");

                    b.ToTable("PaymentAttempts");
                });

            modelBuilder.Entity("TrialBookingApp.Web.Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StudentId");

                    b.HasIndex("ParentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("TrialBookingApp.Web.Domain.Entities.TrialClass", b =>
                {
                    b.Property<Guid>("TrialClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ConfirmedBookingCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrialClassCapacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("TrialClassEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TrialClassStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrialClassTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TrialClassId");

                    b.HasIndex("TrialClassStartDate");

                    b.ToTable("TrialClasses");
                });

            modelBuilder.Entity("TrialBookingApp.Web.Domain.Entities.Booking", b =>
                {
                    b.HasOne("TrialBookingApp.Web.Domain.Entities.Student", "Student")
                        .WithMany("Bookings")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrialBookingApp.Web.Domain.Entities.TrialClass", "TrialClass")
                        .WithMany("TrialClassBookings")
                        .HasForeignKey("TrialClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("TrialClass");
                });

            modelBuilder.Entity("TrialBookingApp.Web.Domain.Entities.PaymentAttempt", b =>
                {
                    b.HasOne("TrialBookingApp.Web.Domain.Entities.Booking", "Booking")
                        .WithMany("PaymentAttempts")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("TrialBookingApp.Web.Domain.Entities.Student", b =>
                {
                    b.HasOne("TrialBookingApp.Web.Domain.Entities.Parent", "Parent")
                        .WithMany("Students")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TrialBookingApp.Web.Domain.Entities.Booking", b =>
                {
                    b.Navigation("PaymentAttempts");
                });

            modelBuilder.Entity("TrialBookingApp.Web.Domain.Entities.Parent", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("TrialBookingApp.Web.Domain.Entities.Student", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("TrialBookingApp.Web.Domain.Entities.TrialClass", b =>
                {
                    b.Navigation("TrialClassBookings");
                });
#pragma warning restore 612, 618
        }
    }
}
